# Claude Code GitHub Action
# Enables @claude mentions in PR comments to trigger Claude Code
# Install with: /install-github-action in Claude Code

name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-response:
    # Only run if comment mentions @claude
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
        
      - name: Extract instruction from comment
        id: extract
        run: |
          COMMENT="${{ github.event.comment.body }}"
          # Remove @claude mention and extract instruction
          INSTRUCTION=$(echo "$COMMENT" | sed 's/@claude//g' | xargs)
          echo "instruction=$INSTRUCTION" >> $GITHUB_OUTPUT
          
      - name: Run Claude Code
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          claude-code --non-interactive \
            --instruction "${{ steps.extract.outputs.instruction }}" \
            --context "PR #${{ github.event.issue.number || github.event.pull_request.number }}"
            
      - name: Commit changes if any
        run: |
          git config --local user.email "claude[bot]@users.noreply.github.com"
          git config --local user.name "claude[bot]"
          git add -A
          git diff --staged --quiet || git commit -m "Claude Code: ${{ steps.extract.outputs.instruction }}"
          git push || echo "No changes to push"

# Usage in PR comments:
# @claude add this fix to CLAUDE.md
# @claude update the documentation for this change
# @claude add a test for this edge case
